server:
  port: 8080

spring:
  application:
    name: testJava2020
  datasource:
    url: jdbc:h2:file:./data/testJava2020
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    defer-datasource-initialization: true
  mvc:
    format:
      date-time: iso
  sql:
    init:
      mode: always


