server:
  port: 8080

spring:
  application:
    name: testJava2020
  datasource:
    url: jdbc:h2:mem:testJava2020
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always

priceApis:
  prices:
    url: http://localhost:${server.port}/price/{applyDate}&{productId}&{brandId}

price:
  url: http://localhost:${server.port}/price
